import { NextResponse } from "next/server";
import { sql } from "@/lib/db";
import { checkAdmin, adminDenialResponse } from "@/lib/auth";
import { parseDate, parseOptionalId, escapeLike, errorResponse } from "@/lib/ledger";

/**
 * The combined statement: both kinds interleaved in date order with a running
 * balance. This is the view a treasurer reads out at a meeting, and neither the
 * contributions nor the expenditures endpoint can produce it — each sees only
 * one direction, so neither can say what the balance was on any given date.
 *
 * The running balance comes from a SQL window function over `signed_amount`,
 * whose sign is generated by the schema. It is computed over the *whole*
 * ledger, ordered by (date, id), and only then filtered to the requested
 * range — so a date-filtered statement still opens at the correct balance
 * instead of restarting from zero.
 */
export async function GET(req: Request) {
  const check = await checkAdmin();
  if (!check.ok) return adminDenialResponse(check);

  try {
    const params = new URL(req.url).searchParams;
    const limitRaw = params.get("limit");
    const limit = limitRaw ? Number(limitRaw) : 200;
    const safeLimit =
      Number.isInteger(limit) && limit > 0 && limit <= 1000 ? limit : 200;

    const where: string[] = [];
    const values: (string | number)[] = [];

    const from = params.get("from");
    if (from) {
      values.push(parseDate(from));
      where.push(`r.date >= $${values.length}`);
    }
    const to = params.get("to");
    if (to) {
      values.push(parseDate(to));
      where.push(`r.date <= $${values.length}`);
    }
    const projectId = parseOptionalId(params.get("projectId"));
    if (projectId !== undefined) {
      values.push(projectId);
      where.push(`r.project_id = $${values.length}`);
    }
    const kind = params.get("kind");
    if (kind === "contribution" || kind === "expenditure") {
      values.push(kind);
      where.push(`r.kind = $${values.length}`);
    }
    const q = (params.get("q") ?? "").trim();
    if (q) {
      values.push(`%${escapeLike(q)}%`);
      where.push(`r.counterparty ILIKE $${values.length} ESCAPE '\\'`);
    }
    const whereSql = where.length ? `WHERE ${where.join(" AND ")}` : "";

    const listText = `
      WITH running AS (
        SELECT
          l.id,
          l.kind,
          l.amount,
          l.signed_amount,
          l.date,
          l.category,
          l.method,
          l.reference,
          l.notes,
          l.project_id,
          p.name AS project_name,
          COALESCE(u.name, l.payee) AS counterparty,
          SUM(l.signed_amount) OVER (
            ORDER BY l.date, l.id
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
          ) AS running_balance
        FROM ledger_live l
        LEFT JOIN users u ON u.id = l.user_id
        LEFT JOIN projects p ON p.id = l.project_id
      )
      SELECT
        r.id, r.kind, r.amount::text AS amount,
        r.signed_amount::text AS signed_amount,
        r.running_balance::text AS running_balance,
        r.date::text AS date, r.category, r.method, r.reference, r.notes,
        r.project_id, r.project_name, r.counterparty
      FROM running r
      ${whereSql}
      ORDER BY r.date DESC, r.id DESC
      LIMIT $${values.length + 1}
    `;

    const totalsText = `
      WITH running AS (
        SELECT l.id, l.kind, l.amount, l.date, l.project_id,
               COALESCE(u.name, l.payee) AS counterparty
        FROM ledger_live l
        LEFT JOIN users u ON u.id = l.user_id
      )
      SELECT
        COALESCE(SUM(r.amount) FILTER (WHERE r.kind = 'contribution'), 0)::text AS total_in,
        COALESCE(SUM(r.amount) FILTER (WHERE r.kind = 'expenditure'), 0)::text  AS total_out,
        COUNT(*)::int AS count
      FROM running r
      ${whereSql}
    `;

    const [list, totals, position] = await Promise.all([
      sql.query(listText, [...values, safeLimit]),
      sql.query(totalsText, values),
      sql`SELECT total_raised::text AS total_raised,
                 total_spent::text  AS total_spent,
                 balance::text      AS balance
          FROM fund_position`,
    ]);

    return NextResponse.json({
      entries: list.rows,
      totalIn: totals.rows[0]?.total_in ?? "0",
      totalOut: totals.rows[0]?.total_out ?? "0",
      count: totals.rows[0]?.count ?? 0,
      shown: list.rows.length,
      position: position.rows[0] ?? {
        total_raised: "0",
        total_spent: "0",
        balance: "0",
      },
    });
  } catch (err) {
    const { body, status } = errorResponse(err);
    return NextResponse.json(body, { status });
  }
}
